// NOTE: This file is NOT autogenerated and contains custom transformers,
//       which are used in the message_transformer.go

package transform

import "github.com/bold-commerce/protoc-gen-struct-transformer/example"

// PbCustomTypeToStringPtrVal is an example of the custom transformer from Pb to go
func PbCustomTypeToStringPtrVal(src *example.CustomType, opts ...TransformParam) string {
	applyOptions(opts...)

	if version == "v2" {
		return src.Value
	}

	return ""
}

// StringToPbCustomTypeValPtr is an example of the custom transformer from go to Pb
func StringToPbCustomTypeValPtr(src string, opts ...TransformParam) *example.CustomType {
	applyOptions(opts...)

	if version == "v2" {
		return &example.CustomType{
			Value: src,
		}
	}

	return nil
}
