language: go

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - GO111MODULE=off go get github.com/onsi/gomega
  - GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo
  - go mod download
  - go mod verify

script:
  - ginkgo -r -race

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
