// Code generated by protoc-gen-struct-transformer, version: <dev>. DO NOT EDIT.

package transform

var version string

// TransformParam is a function option type.
type TransformParam func()

// WithVersion sets global version variable.
func WithVersion(v string) TransformParam {
	return func() {
		version = v
	}
}

func applyOptions(opts ...TransformParam) {
	for _, o := range opts {
		o()
	}
}
