name: Pull Request

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  go-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run tests
        run: ginkgo -r
